### ISSUE TITLE
Libernet Support for Arcadyan AW1000

### ISSUE THREAD

**Issue by cjayacopra** [NevermoreSSH/openwrt-packages2#1]
Hi there!

May I humbly ask if you can add Libernet to this custom immortalwrt Image?

https://github.com/lutfailham96/libernet

Thank you so much!

**Comment by NevermoreSSH** [comment]
hi, i cant compile include libernet cuz some user memory aw1000 only around 64mb. if someone install maybe will brick. Also this repo outdated, using old repo openwrt 21.

i suggest u can try install and add customfeed repo openwrt 21.
```
src/gz immortalwrt_package_custom https://downloads.immortalwrt.org/releases/21.02.7/packages/aarch64_cortex-a53/packages
```
SSH will not working probably, u need **badvpn** & **corkscrew**. TQ

**Comment by NevermoreSSH** [comment]
or u can use this 2nd method. after install u can see libernetplus at menu. u can try n error working or not. 60mb space memory requirement.TQ

```
wget -q -O installer4 https://raw.githubusercontent.com/NevermoreSSH/openwrt-packages2/main/libernetplus/libernet.sh; chmod 755 installer4; sh installer4; reboot
```

**Comment by cjayacopra** [comment]
Will try that second method. Thank you so much. Will get back to you with an update.

I think this no way to install if the requirements is 60mb user space. The fw only got 24mb of total. Even if I remove some more packages. Is there a way you can modify your libernetplus to only use SSH? no other protocols so that it can be the smallest possible?

**Comment by cjayacopra** [comment]
![image](https://github.com/NevermoreSSH/openwrt-packages2/assets/83209495/fbec28ac-5374-483c-be25-ebcea9d7dc77)


I'm having this error. I think the storage issue can be fixed using extroot. However, there's another error in the script.


Since I do not have an available flashdrive to use as extroot at the moment, may I kindly request to trim down libernet to use SSH only? Remove v2ray/xray, openvpn, trojan and shadowsocks?

**Comment by cjayacopra** [comment]
![image](https://github.com/NevermoreSSH/openwrt-packages2/assets/83209495/7d89b938-5235-45a4-b5ef-b8a7d200ca93)

An update, I was able to install the libernetplus with the help of extroot to suffice the storage. However, the uci commands are still having an error ```uci: Parse error (invalid command) at line 4, byte 0```. May I kindly ask assistance about this? I'm nowhere near being beginner. I'm a total noob, Sorry about that

**Comment by NevermoreSSH** [comment]
U can leave it that uci error. Thats command for openwrt, nothing problem. U can try n error that apps. Libernet also outdated 2/3year past, so it wont working with latest custom payload.

**Comment by cjayacopra** [comment]
I see. That's why. So I think it's safe to assume that this is now solved. However, May I ask for you to check on this one repo and check if this can be implemented in your FW for arcadyan? This works so well on a linux machine but I cannot make it work with OpenWrt.

https://github.com/abdoxfox/HTTP-CUSTOM-HEADERS-VPN
